### ISSUE TITLE
Upgrade pylint

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-scraper#114]
Upgrade pylint (like in this PR https://github.com/meilisearch/docs-scraper/pull/113) and fix the linter errors.

**Comment by AABur** [comment]
Linter errors are caused by duplicate code in tests. I suggest parameterising the tests with `@pytest.mark.parametrize` and `@pytest.fixtures`. Then common fixtures can be put in `conftest.py`

I have made changes to a few tests. If you agree with this method, I will continue to work on this issue.

https://github.com/AABur/docs-scraper/commits/upgrade_pylint-2.7.4

**Comment by AABur** [comment]
This issue is obsolete and I think it should be closed.

**Comment by bidoubiwa** [comment]
Thanks a lot @AABur
